Feature/121
bimser-intern/docs pull request #131
Opened 2022-08-04 14:51 UTC by om3rd

#121

2022-08-04 14:58 UTC, burakkucukk approved these changes

2022-08-04 15:02 UTC, burakkucukk approved these changes

2022-08-04 15:03 UTC, muhammetduzenli submitted a review, later dismissed

2022-08-04 15:05 UTC, SimgeTerzioglu submitted a review, later dismissed

2022-08-04 19:34 UTC, perteka requested changes
README.md dosyasında 87.satırdaki metin 64.satırda olması gerekiyor.

2022-08-05 05:57 UTC, otipirdamaz requested changes

2022-08-05 05:57 UTC, otipirdamaz commented on README.md
> +
Bu boşlukların olmaması gerekiyor

2022-08-05 09:04 UTC, otipirdamaz approved these changes

2022-08-05 09:05 UTC, muhammetduzenli approved these changes

2022-08-05 09:05 UTC, selincengiz41 approved these changes

2022-08-05 09:06 UTC, perteka approved these changes

2022-08-05 09:06 UTC, omerhamsi approved these changes

2022-08-05 09:26 UTC, ummugulsumm requested changes
38. satırda cümlenin sonunda nokta eksik olmuş

2022-08-05 11:09 UTC, SimgeTerzioglu approved these changes

2022-08-05 11:20 UTC, ummugulsumm approved these changes

2022-08-05 11:22 UTC, merged