[feature] - [126] - [semver:minor] - Diary eklendi
bimser-intern/docs pull request #137
Opened 2022-08-04 15:26 UTC by SimgeTerzioglu

#126

2022-08-04 15:27 UTC, om3rd approved these changes

2022-08-04 16:02 UTC, ummugulsumm requested changes
31. satırdaki 'Burada' kelimesinde bir hata olmuş sanırım

2022-08-04 16:15 UTC, ummugulsumm approved these changes

2022-08-04 16:45 UTC, esrayelmen approved these changes

2022-08-04 18:27 UTC, perteka approved these changes

2022-08-04 19:26 UTC, om3rd approved these changes

2022-08-04 20:42 UTC, muhammetduzenli approved these changes

2022-08-05 05:57 UTC, Keremerk approved these changes

2022-08-05 05:58 UTC, otipirdamaz approved these changes

2022-08-05 05:58 UTC, merged