[feature] - [136] - [semver:minor] - diary eklendi
bimser-intern/docs pull request #138
Opened 2022-08-04 16:06 UTC by perteka

#136

2022-08-04 16:19 UTC, ummugulsumm requested changes
19. ve 24. satırlarda yazım yanlışları var

2022-08-04 18:12 UTC, ummugulsumm approved these changes

2022-08-04 18:16 UTC, enisearslan approved these changes

2022-08-05 04:28 UTC, muhammetduzenli approved these changes

2022-08-05 05:59 UTC, otipirdamaz approved these changes

2022-08-05 06:01 UTC, Keremerk approved these changes

2022-08-05 06:23 UTC, omerhamsi approved these changes

2022-08-05 08:07 UTC, selincengiz41 approved these changes

2022-08-05 09:28 UTC, ummugulsumm approved these changes

2022-08-05 09:31 UTC, merged