[feature] - [152] - [semver:minor] - diary güncellendi
bimser-intern/docs pull request #153
Opened 2022-08-04 20:21 UTC by burakkucukk

#152

2022-08-04 20:24 UTC, om3rd submitted a review, later dismissed

2022-08-04 20:30 UTC, enisearslan submitted a review, later dismissed

2022-08-04 20:45 UTC, SimgeTerzioglu submitted a review, later dismissed

2022-08-04 20:45 UTC, ummugulsumm requested changes
Dokumantasyon kelimesi TDK'de dokümantasyon olarak geçiyor, 
13. satırda cümlenin sonunda nokta eksik,
Bir de sayfadaki linklerden önce bir boşluk bırakabilirsin, cümlelerde olduğu gibi

2022-08-04 20:54 UTC, esrayelmen submitted a review, later dismissed

2022-08-05 08:09 UTC, selincengiz41 approved these changes

2022-08-05 10:53 UTC, perteka submitted a review, later dismissed

2022-08-05 12:38 UTC, otipirdamaz approved these changes

2022-08-05 12:40 UTC, selincengiz41 approved these changes

2022-08-05 12:42 UTC, omerhamsi approved these changes

2022-08-05 13:16 UTC, ummugulsumm approved these changes

2022-08-05 13:30 UTC, felataslan approved these changes

2022-08-05 14:20 UTC, muhammetduzenli approved these changes

2022-08-05 17:34 UTC, merged