[feature] - [162] - [semver:minor] - Diary güncellendi
bimser-intern/docs pull request #163
Opened 2022-08-05 14:00 UTC by om3rd

#162

2022-08-05 14:18 UTC, muhammetduzenli submitted a review, later dismissed

2022-08-05 14:18 UTC, omerhamsi approved these changes

2022-08-05 14:24 UTC, ummugulsumm requested changes
Link vermeden önce bir boşluk bırakabilirsin, cümleler arasında olduğu gibi

2022-08-05 17:19 UTC, om3rd commented
> Link vermeden önce bir boşluk bırakabilirsin, cümleler arasında olduğu gibi

Düzeltildi.

2022-08-05 18:06 UTC, burakkucukk approved these changes

2022-08-05 18:13 UTC, muhammetduzenli approved these changes

2022-08-05 20:07 UTC, ummugulsumm approved these changes

2022-08-06 05:19 UTC, perteka approved these changes

2022-08-06 09:58 UTC, ummugulsumm approved these changes

2022-08-06 12:49 UTC, enisearslan approved these changes

2022-08-06 12:49 UTC, oykumotor approved these changes

2022-08-06 12:49 UTC, merged