[feature] - [176] - [semver:minor] - diary güncellendi.
bimser-intern/docs pull request #177
Opened 2022-08-05 16:25 UTC by enisearslan

2022-08-05 16:38 UTC, muhammetduzenli requested changes
Günlüğünde problem yok fakat sanırım yanlışlıkla fazladan "git" diye bir dosya eklemişsin. Onu siler misin ?

2022-08-05 17:20 UTC, muhammetduzenli approved these changes

2022-08-05 18:04 UTC, burakkucukk approved these changes

2022-08-05 21:17 UTC, esrayelmen approved these changes

2022-08-06 05:26 UTC, perteka approved these changes

2022-08-06 12:50 UTC, om3rd approved these changes

2022-08-06 13:11 UTC, oykumotor approved these changes

2022-08-06 13:15 UTC, selincengiz41 approved these changes

2022-08-06 13:17 UTC, merged