[feature] - [192] - [semver:minor] - diary güncellendi
bimser-intern/docs pull request #193
Opened 2022-08-08 19:45 UTC by felataslan

#192

2022-08-08 19:52 UTC, muhammetduzenli approved these changes

2022-08-08 20:05 UTC, esrayelmen reviewed
52. ve 54. satırlarda yazım hataları mevcut.

2022-08-08 20:13 UTC, eraydnci submitted a review, later dismissed

2022-08-08 20:37 UTC, SimgeTerzioglu requested changes
51. satırda iki kere "ile" kelimesi yazılmış.

2022-08-08 21:06 UTC, SimgeTerzioglu approved these changes

2022-08-08 22:14 UTC, burakkucukk approved these changes

2022-08-09 07:15 UTC, omerhamsi approved these changes

2022-08-09 07:23 UTC, muhammetduzenli approved these changes

2022-08-09 08:24 UTC, eraydnci approved these changes

2022-08-09 08:41 UTC, perteka approved these changes

2022-08-09 09:13 UTC, merged