[feature]-[248]-[semver:minor]-Diary güncellendi
bimser-intern/docs pull request #249
Opened 2022-08-10 19:25 UTC by burakkucukk

#248

2022-08-11 06:27 UTC, SimgeTerzioglu approved these changes

2022-08-11 06:41 UTC, perteka approved these changes

2022-08-11 13:38 UTC, om3rd approved these changes

2022-08-11 15:04 UTC, selincengiz41 approved these changes

2022-08-11 18:04 UTC, Keremerk approved these changes

2022-08-12 11:54 UTC, otipirdamaz requested changes

2022-08-12 11:54 UTC, otipirdamaz commented on Interns/BurakKucuk.md
> +-  Software Development Unit Manager Buluşması yapıldı.
başlangıçta iki boşluk var

2022-08-12 11:56 UTC, burakkucukk commented on Interns/BurakKucuk.md
> +-  Software Development Unit Manager Buluşması yapıldı.
diğer #261 de düzenledim

2022-08-12 11:58 UTC, otipirdamaz commented on Interns/BurakKucuk.md
> +-  Software Development Unit Manager Buluşması yapıldı.
bu pr geçersiz mi o zaman diğerini kabul etmemiz yeterli mi?

2022-08-12 12:04 UTC, closed without merging