[feature]-[261]-[semver:minor]-Diary güncellendi
bimser-intern/docs pull request #264
Opened 2022-08-11 16:39 UTC by burakkucukk

#261

2022-08-11 18:11 UTC, Keremerk requested changes
Katılındı yerine katınıldı yazmışsın onu düzeltebilir misin ?
"Daily scrum toplantısına katınıldı."

2022-08-11 18:20 UTC, SimgeTerzioglu approved these changes

2022-08-11 21:01 UTC, esrayelmen approved these changes

2022-08-11 21:08 UTC, perteka submitted a review, later dismissed

2022-08-12 05:57 UTC, Keremerk approved these changes

2022-08-12 11:49 UTC, enisearslan approved these changes

2022-08-12 11:54 UTC, otipirdamaz approved these changes

2022-08-12 11:57 UTC, om3rd approved these changes

2022-08-12 12:01 UTC, SimgeTerzioglu approved these changes

2022-08-12 17:59 UTC, eraydnci approved these changes

2022-08-12 17:59 UTC, merged