[feature]-[262]-[semver:minor]-Diary güncellendi
bimser-intern/docs pull request #265
Opened 2022-08-11 16:46 UTC by eraydnci

#262

2022-08-11 17:24 UTC, felataslan submitted a review, later dismissed

2022-08-11 18:21 UTC, SimgeTerzioglu approved these changes

2022-08-11 18:57 UTC, om3rd submitted a review, later dismissed

2022-08-11 19:27 UTC, ummugulsumm requested changes
115. satırda yazım hatası olmuş

2022-08-11 19:48 UTC, rahimeT approved these changes

2022-08-11 19:48 UTC, rahimeT approved these changes

2022-08-11 21:01 UTC, esrayelmen approved these changes

2022-08-11 21:04 UTC, perteka submitted a review, later dismissed

2022-08-12 06:24 UTC, eraydnci commented
> 115. satırda yazım hatası olmuş

Düzeltildi. Teşekkürler

2022-08-12 06:26 UTC, felataslan approved these changes

2022-08-12 06:28 UTC, felataslan approved these changes

2022-08-12 07:03 UTC, burakkucukk approved these changes

2022-08-12 07:14 UTC, ummugulsumm approved these changes

2022-08-12 07:21 UTC, esrayelmen approved these changes

2022-08-12 08:06 UTC, perteka approved these changes

2022-08-12 08:23 UTC, SimgeTerzioglu approved these changes

2022-08-12 08:23 UTC, merged