[feature]-[504]-[semver:minor]-Frontend Sunumu eklendi.
bimser-intern/docs pull request #505
Opened 2022-08-27 08:09 UTC by felataslan

#504 
- Frontend sunumu eklendi.

2022-08-27 09:53 UTC, Keremerk requested changes
readme'de 22 ye koyarsan conflifct olucak benim pr'ımla

2022-08-28 13:50 UTC, esrayelmen approved these changes

2022-08-28 17:38 UTC, om3rd approved these changes

2022-08-29 06:47 UTC, om3rd submitted a review, later dismissed

2022-08-29 10:09 UTC, Keremerk approved these changes

2022-08-29 16:05 UTC, eraydnci approved these changes

2022-08-29 22:03 UTC, esrayelmen submitted a review, later dismissed

2022-08-30 06:54 UTC, SimgeTerzioglu submitted a review, later dismissed

2022-08-30 07:34 UTC, eraydnci submitted a review, later dismissed

2022-08-30 08:23 UTC, om3rd submitted a review, later dismissed

2022-08-30 18:30 UTC, rahimeT submitted a review, later dismissed

2022-08-31 04:28 UTC, SimgeTerzioglu submitted a review, later dismissed

2022-08-31 05:56 UTC, perteka submitted a review, later dismissed

2022-08-31 06:29 UTC, omerhamsi submitted a review, later dismissed

2022-08-31 16:15 UTC, muhammetduzenli approved these changes

2022-08-31 17:11 UTC, eraydnci approved these changes

2022-08-31 17:23 UTC, rahimeT approved these changes

2022-09-01 00:48 UTC, perteka approved these changes

2022-09-01 05:57 UTC, omerhamsi approved these changes

2022-09-01 15:20 UTC, perteka approved these changes

2022-09-01 15:38 UTC, muhammetduzenli approved these changes

2022-09-01 16:28 UTC, eraydnci approved these changes

2022-09-01 16:31 UTC, SimgeTerzioglu approved these changes

2022-09-01 16:40 UTC, omerhamsi approved these changes

2022-09-01 16:40 UTC, merged