[feature]-[508]-[semver:minor]-Diary güncellendi.
bimser-intern/docs pull request #510
Opened 2022-08-29 12:08 UTC by arifrizagull

2022-08-29 12:19 UTC, otipirdamaz requested changes
ana readme dosyasına ilişkilendirme yapılmamış

2022-08-29 12:19 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> + - Sprint Planning toplantısına katılım sağlandı.
Sprint Planning -> Sprint review olmalı

2022-08-29 12:19 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> +- Web ve android test senaryoları yazıldı.
üst satırlarla hizalamalar farklı

2022-08-29 12:19 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> +- Daily scrum yapıldı.
üst satırlarla hizalamalar farklı

2022-08-29 12:38 UTC, om3rd submitted a review, later dismissed

2022-08-29 13:10 UTC, otipirdamaz requested changes

2022-08-29 13:10 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> + - Sprint Planning toplantısına katılım sağlandı.
bu düzeltilmemiş

2022-08-29 13:20 UTC, otipirdamaz requested changes

2022-08-29 13:20 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> +
boşluk kalmış

2022-08-29 13:51 UTC, otipirdamaz requested changes

2022-08-29 13:51 UTC, otipirdamaz commented on Interns/ArifRızaGül.md
> +
Burada da fazla boşluk var

2022-08-30 17:25 UTC, otipirdamaz requested changes
Tester.md dosyasını ayrı bir pr ile göndermen lazım. Onu bu pr dan çıkaralım. Commit mesajı da diary güncellendi değil her zaman ne yaptıysan onu yazmalısın

2022-08-30 20:09 UTC, omerhamsi approved these changes

2022-08-30 20:10 UTC, Keremerk approved these changes

2022-08-30 20:18 UTC, Keremerk approved these changes

2022-08-30 21:49 UTC, otipirdamaz approved these changes

2022-08-31 04:26 UTC, SimgeTerzioglu approved these changes

2022-08-31 05:48 UTC, om3rd approved these changes

2022-08-31 05:49 UTC, eraydnci approved these changes

2022-08-31 05:53 UTC, muhammetduzenli approved these changes

2022-08-31 05:54 UTC, merged