[feature]-[530]-[semver:minor]-Tester Sunumu Eklendi
bimser-intern/docs pull request #531
Opened 2022-08-30 19:35 UTC by arifrizagull

#530

2022-08-30 19:36 UTC, om3rd submitted a review, later dismissed

2022-08-30 19:48 UTC, otipirdamaz requested changes
Ana readme dosyasına yönlendirme eklenmeli

2022-08-30 20:05 UTC, otipirdamaz requested changes
Bu pr da günlüğünle ilgili eklemeler olmamalı her pr sadece tanımlı olan işle ilgili geliştirmeleri kapsamalı

2022-08-30 21:52 UTC, otipirdamaz submitted a review, later dismissed

2022-08-31 05:56 UTC, perteka approved these changes

2022-08-31 06:21 UTC, esrayelmen submitted a review, later dismissed

2022-08-31 06:31 UTC, rahimeT approved these changes

2022-08-31 06:34 UTC, eraydnci submitted a review, later dismissed

2022-08-31 06:34 UTC, felataslan approved these changes

2022-08-31 07:03 UTC, muhammetduzenli approved these changes

2022-08-31 07:05 UTC, otipirdamaz approved these changes

2022-08-31 07:08 UTC, rahimeT approved these changes

2022-08-31 07:10 UTC, esrayelmen approved these changes

2022-08-31 07:24 UTC, perteka approved these changes

2022-08-31 07:25 UTC, enisearslan approved these changes

2022-08-31 07:25 UTC, merged