[feature]-[542]-[semver:minor]-Diary güncellendi
bimser-intern/docs pull request #543
Opened 2022-08-31 18:27 UTC by Keremerk

2022-08-31 18:28 UTC, om3rd approved these changes

2022-08-31 18:33 UTC, felataslan requested changes

2022-08-31 18:33 UTC, felataslan commented on Interns/KeremErkubilay.md
> +[**29.08.2022**](https://github.com/bimser-intern/docs/issues/542)
Tarihi yanlış yazmışsın

2022-08-31 18:44 UTC, rahimeT approved these changes

2022-08-31 18:58 UTC, esrayelmen approved these changes

2022-09-01 00:52 UTC, perteka approved these changes

2022-09-01 05:21 UTC, felataslan approved these changes

2022-09-01 05:50 UTC, om3rd approved these changes

2022-09-01 08:07 UTC, eraydnci approved these changes

2022-09-01 08:07 UTC, merged