[feature] - [88] - [semver:minor] - diary eklendi
bimser-intern/docs pull request #90
Opened 2022-08-03 13:35 UTC by muhammetduzenli

#88

2022-08-03 13:39 UTC, otipirdamaz requested changes
Ana sayfadaki readme.md dosyasına da erişim linkini ekleyebilir misin?

2022-08-03 15:19 UTC, otipirdamaz commented
conflict oluşmuş rebase master yapman gerekiyor

2022-08-03 17:40 UTC, muhammetduzenli commented
> conflict oluşmuş rebase master yapman gerekiyor

conflict oluşmasına sebep olan satırlar düzeltildi.

2022-08-04 05:53 UTC, otipirdamaz approved these changes

2022-08-04 05:53 UTC, Keremerk approved these changes

2022-08-04 05:56 UTC, om3rd approved these changes

2022-08-04 06:14 UTC, omerhamsi approved these changes

2022-08-04 06:15 UTC, felataslan approved these changes

2022-08-04 06:17 UTC, perteka approved these changes

2022-08-04 06:17 UTC, merged