[feature] - [86] - [semver:minor] - Diary eklendi
bimser-intern/docs pull request #91
Opened 2022-08-03 13:39 UTC by Keremerk

#86  İlk üç gün için diary eklendi.

2022-08-03 13:43 UTC, otipirdamaz requested changes

2022-08-03 13:43 UTC, otipirdamaz commented on Interns/KeremErkubilay.md
> +İlk yaz stajımı Düzce Üniversitesi Bilgi İşlemde yaptım. Bu sene ise **Bimser** bana staj yapma fırsatı verdi. içinde bulunduğum ekiple beraber güzel bir proje çıkarmaya çalışacağız.
İçinde büyük harf ile başlamalı.

Bir de ana sayfaya da erişim linkini ekleyelim

2022-08-03 13:43 UTC, otipirdamaz commented on Interns/KeremErkubilay.md
> +  [**03.08.2022**]
Diğer başlıklarla aynı hizada değil

2022-08-03 14:45 UTC, Keremerk commented on Interns/KeremErkubilay.md
> +  [**03.08.2022**]
Hatalar giderildi.

2022-08-03 14:46 UTC, Keremerk commented on Interns/KeremErkubilay.md
> +İlk yaz stajımı Düzce Üniversitesi Bilgi İşlemde yaptım. Bu sene ise **Bimser** bana staj yapma fırsatı verdi. içinde bulunduğum ekiple beraber güzel bir proje çıkarmaya çalışacağız.
Hatalar giderildi.

2022-08-03 14:55 UTC, otipirdamaz approved these changes

2022-08-03 14:57 UTC, selincengiz41 submitted a review, later dismissed

2022-08-03 14:59 UTC, otipirdamaz submitted a review, later dismissed

2022-08-03 15:01 UTC, selincengiz41 submitted a review, later dismissed

2022-08-03 15:14 UTC, muhammetduzenli approved these changes

2022-08-03 19:45 UTC, omerhamsi submitted a review, later dismissed

2022-08-04 06:03 UTC, burakkucukk submitted a review, later dismissed

2022-08-04 06:20 UTC, muhammetduzenli submitted a review, later dismissed

2022-08-04 06:21 UTC, enisearslan approved these changes

2022-08-04 06:22 UTC, om3rd approved these changes

2022-08-04 06:23 UTC, esrayelmen approved these changes

2022-08-04 06:40 UTC, SimgeTerzioglu submitted a review, later dismissed

2022-08-04 06:54 UTC, oykumotor approved these changes

2022-08-04 06:55 UTC, oykumotor approved these changes

2022-08-04 06:55 UTC, enisearslan approved these changes

2022-08-04 06:56 UTC, otipirdamaz approved these changes

2022-08-04 06:57 UTC, om3rd approved these changes

2022-08-04 07:00 UTC, muhammetduzenli approved these changes

2022-08-04 07:12 UTC, omerhamsi approved these changes

2022-08-04 07:12 UTC, SimgeTerzioglu approved these changes

2022-08-04 07:12 UTC, merged