[feature] - [92] - [semver:minor] - diary eklendi
bimser-intern/docs pull request #97
Opened 2022-08-03 14:09 UTC by felataslan

#92

2022-08-03 14:59 UTC, selincengiz41 requested changes
Readme.md dosyasına bağlantı linki eklemeniz lazım

2022-08-03 16:37 UTC, abdullahbodur approved these changes

2022-08-04 05:52 UTC, selincengiz41 submitted a review, later dismissed

2022-08-04 05:54 UTC, Keremerk submitted a review, later dismissed

2022-08-04 05:55 UTC, om3rd approved these changes

2022-08-04 06:04 UTC, burakkucukk approved these changes

2022-08-04 06:17 UTC, omerhamsi approved these changes

2022-08-04 06:21 UTC, muhammetduzenli submitted a review, later dismissed

2022-08-04 06:22 UTC, esrayelmen approved these changes

2022-08-04 06:22 UTC, enisearslan submitted a review, later dismissed

2022-08-04 06:41 UTC, selincengiz41 reviewed
Conflict oluşmuş , onu çözmen gerekiyor eklemeden önce

2022-08-04 07:30 UTC, muhammetduzenli submitted a review, later dismissed

2022-08-04 07:31 UTC, otipirdamaz approved these changes

2022-08-04 07:33 UTC, omerhamsi approved these changes

2022-08-04 07:33 UTC, selincengiz41 submitted a review, later dismissed

2022-08-04 08:15 UTC, oykumotor submitted a review, later dismissed

2022-08-04 08:16 UTC, enisearslan approved these changes

2022-08-04 08:18 UTC, om3rd approved these changes

2022-08-04 08:20 UTC, otipirdamaz approved these changes

2022-08-04 08:28 UTC, oykumotor approved these changes

2022-08-04 08:28 UTC, om3rd approved these changes

2022-08-04 08:29 UTC, omerhamsi approved these changes

2022-08-04 08:29 UTC, enisearslan approved these changes

2022-08-04 08:31 UTC, selincengiz41 approved these changes

2022-08-04 08:32 UTC, merged